quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes_site.urls")),
    path("users/", include("users.urls"))
]

quotes/quotes_site/urls.py
from . import views
from django.urls import path

app_name = 'quotes_site'
urlpatterns = [
    path("", views.index, name="index"),
    path('<int:id>/', views.author_details, name='author_details'),
    path('add_author', views.add_author, name="add_author"),
    path('add_quote', views.add_quote, name="add_quote")
]

quotes/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .forms import LoginForm
from .views import RegisterView

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                     authentication_form=LoginForm), name="login"),
    path("logout/", LogoutView.as_view(template_name="users/logout.html"), name="logout")
]

quotes/quotes_site/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=250, null=False, unique=True)
    born_date = models.DateField(null=False)
    born_location = models.CharField(max_length=250, null=False)
    description = models.TextField(null=False)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    text = models.TextField(null=False)
    tags = models.ManyToManyField(Tag, related_name='quotes')

    author = models.ForeignKey(
        Author, on_delete=models.SET_NULL, null=True, related_name="quotes")

    def __str__(self):
        return f"{self.author.fullname}: '{self.text[:30]}...'"

quotes/users/models.py
from django.db import models

# Create your models here.

quotes/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    password1 = forms.CharField(max_length=50,  required=True, widget=forms.PasswordInput(attrs={"class": "form-control"}))
    password2 = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    password = forms.CharField(max_length=50,  required=True, widget=forms.PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ['username', 'password']

quotes/quotes_site/views.py
from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from .forms import AuthorForm, QuoteForm
from .models import Quote, Tag, Author


def get_top10tags():
    tags = Tag.objects.all()
    topTenTags: list = sorted(tags, key=lambda tag: (tag.quotes.all().count(), tag.name), reverse=True)[:10]
    return topTenTags


def index(request):
    quotes = Quote.objects.all().order_by("-id")
    topTenTags = get_top10tags()

    tag_name = request.GET.get('tag_name')
    if tag_name:
        try:
            tag_id = Tag.objects.get(name=tag_name.capitalize()).id
            quotes = quotes.filter(tags__in=[tag_id])
        except Tag.DoesNotExist as e:
            quotes = []

    paginator = Paginator(quotes, 4)
    page = request.GET.get('page')
    quotes = paginator.get_page(page)

    return render(request, "quotes_site/index.html", {"quotes": quotes, "topTenTags": topTenTags})


def author_details(request, id):
    author = Author.objects.get(pk=id)

    return render(request, "quotes_site/author_details.html", {"author": author})


@login_required
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quotes_site:index')

        return render(request, 'quotes_site/add_author.html', {'form': form})

    return render(request, "quotes_site/add_author.html", {'form': AuthorForm()})


@login_required
def add_quote(request):
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quotes_site:index')

        return render(request, 'quotes_site/add_quote.html', {'form': form})

    return render(request, "quotes_site/add_quote.html", {'form': QuoteForm()})

quotes/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import RegisterForm, LoginForm


class RegisterView(View):
    form_class = RegisterForm
    template_name = 'users/register.html'

    def dispatch(self, request,  *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="quotes_site:index")
        return super(RegisterView, self).dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {"form": self.form_class()})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, f"Your account was successfully created!")
            return redirect(to="users:login")

        return render(request, self.template_name, {"form": self.form_class()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect('users:logout')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes_site:index')

    return render(request, 'users/login.html', context={"form": LoginForm()})

quotes/quotes_site/templates/quotes_site/includes/quote.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
{% block body %}
    <figure class="bg-light p-4" style="border-left: .35rem solid #fcdb5e; border-top: 1px solid #eee; border-right: 1px solid #eee; border-bottom: 1px solid #eee;">
        <i class="fas fa-quote-left fa-2x mb-4" style="color: #fcdb5e;"></i>
        <blockquote class="blockquote pb-2">
            <p>"{{ quote.text }}"</p>
        </blockquote>
        <figcaption class="blockquote-footer mb-0">
            <h5> By <cite><a href="{% url 'quotes_site:author_details' quote.author.id %}" class="link-info">{{ quote.author.fullname }}</a></cite></h5>
        </figcaption>
        <br>
        <h5>Tags: 
            {% for tag in quote.tags.all %}
                <a type="submit" class="btn btn-primary btn-sm" name="tag_name" href="?tag_name={{ tag.name }}">{{ tag }}</a>
            {% endfor %}
        </h5>
    </figure>
    <br>


  
{% endblock body %}

quotes/quotes_site/templates/quotes_site/includes/top_tags.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
{% block body %}
<div class="card" >
    <div class="card-header" style="text-align: center;">
      <h3>Top 10 tags</h3>
    </div>
    <ul class="list-group list-group-flush" style="text-align: center;">
        {% for tag in topTenTags %}
            <li class="list-group-item"><a type="submit" class="btn btn-success btn-sm" name="tag_name" href="?tag_name={{ tag.name }}">{{ tag }}</a></li>
        {% endfor %}
    </ul>
  </div>

{% endblock body%}

quotes/quotes_site/templates/quotes_site/index.html
{% extends 'quotes_site/base.html' %}

{% block body %}

<br>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form class="card card-sm">
                <div class="card-body row no-gutters align-items-center">
                    <div class="col">
                        <input type="search" name="tag_name" placeholder="Search for tag" class="form-control form-control">
                    </div>
                    <div class="col-auto">
                        <button class="btn btn-warning" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
<br>

<div class="container">
    <div class="row">
        <div class="col-md-10">
            {% for quote in quotes %}
                {% include "quotes_site/includes/quote.html" %}
            {% endfor %}
        </div>
        
        <div class="col-md-2">
            {% include "quotes_site/includes/top_tags.html" %}
        </div>
    </div>
</div>

<div class="row d-flex align-items-center">
    <div class="col-md-4 offset-md-4">
        <ul class="pagination">
            {% if quotes.has_previous %}
                <li class="page-item">
                    <a class="page-link page-link-warning" href="?page={{ quotes.previous_page_number }}">Previous</a>
                </li>
            {% endif %}
            
            <li class="page-item active">
                <a class="page-link" href="?page={{ quotes.number }}">Current</a>
            </li>

                
            {% if quotes.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ quotes.next_page_number }}">Next</a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>

{% endblock body %}

quotes/users/templates/users/login.html
{% extends 'quotes_site/base.html' %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}


{% if form.errors %}
    <div class="alert alert-danger" role="alert">
        <span>{{ form.non_field_errors }}</span>
    </div>
{% endif %} 

{% block body %}
    <div class="container">
        <div class="row">
            <div class="offset-4 col-md-4">
                <form method="post" action="{% url 'users:login' %}">
                    {% csrf_token %}
                    <br>
                    <div>
                        <label> <h3>Username:</h3></label>
                            {{ form.username }}
                        <span>{{ form.errors.username }}</span>
                    </div>
                    <br>

                    <div>
                        <label> <h3>Password:</h3> </label>
                            {{ form.password }}
                        <span>{{ form.errors.password }}</span>
                    </div>
                    <br>
                    <div class="grid d-flex justify-content-between">
                        <button type="submit" class="btn btn-primary">Log In</button>
                        <button type="reset" class="btn btn-secondary">Reset</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock body %}

quotes/users/templates/users/logout.html
{% extends 'quotes_site/base.html' %}

{% block body %}
    <br>
    <h1 style="text-align: center;">See you soon! Goodbye!</h1>
{% endblock body %}

quotes/users/templates/users/register.html
{% extends 'quotes_site/base.html' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="offset-4 col-md-4">
                <form method="POST">
                    {% csrf_token %}
                    <br>
                    <div>
                        <label> <h3>Username:</h3></label>
                            {{ form.username }}
                        <span>{{ form.errors.username }}</span>
                    </div>
                    <br>

                    <div>
                        <label> <h3>Password:</h3> </label>
                            {{ form.password1 }}
                        <span>{{ form.errors.password1 }}</span>
                    </div>
                    <br>

                    <div>
                        <label> <h3>Password confirmation:</h3></label>
                            {{ form.password2 }}
                        <span>{{ form.errors.password2 }}</span>
                    </div>
                    <br>

                    <div class="grid d-flex justify-content-between">
                        <button type="submit" class="btn btn-primary">Sign Up</button>
                        <button type="reset" class="btn btn-secondary">Reset</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock body %}